[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000/**"]

[auth.email]
# 1 day = 86400 seconds
# Expiration settings should be managed in the Supabase Dashboard
# invite_confirm_expire = 86400

[functions.create-user]
verify_jwt = false

[functions.external-dj-links]
verify_jwt = false
